[tox]
env_list = py312,py313,py314
skip_missing_interpreters = true

[testenv]
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --extras mcp
    poetry sync --extras mcp
commands =
    poetry run pytest tests/ --import-mode importlib

